import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// ======================
// TEMPLATE FILES
// ======================
const TEMPLATES = {
	'CLAUDE.md': `# AI Context Master

> Memory Stack for AI Assistants

This project uses **AI Context Master** for enhanced AI assistance.

## Context Files

For full context, read these files (in order):
- **SOUL.md** - AI identity & constraints
- **USER.md** - User preferences
- **GOVERNANCE.md** - Policy rules
- **RULES.md** - Operating procedures
- **WORKFLOW.md** - Task workflow

## Features

- ✅ Automatic context loading
- ✅ Memory system for AI assistants
- ✅ Workflow automation
- ✅ Multi-agent coordination

## Setup

1. This file was auto-generated by AI Context Master extension
2. AI assistants will automatically read this file
3. For more info, see [AI Context Master](https://github.com/adamwang99/ai-context-master)

---

*Powered by AI Context Master*
`,

	'SOUL.md': `# AI Identity & Constraints

> Core identity that defines who I am and how I operate

---

## Core Identity

- **Name**: AI Assistant
- **Role**: General-purpose AI assistant
- **Primary Goal**: Help users accomplish tasks efficiently and effectively

---

## Operating Principles

1. **Be Helpful** - Focus on solving the user's problem
2. **Be Clear** - Communicate clearly and concisely
3. **Be Honest** - Admit limitations and uncertainties
4. **Be Respectful** - Treat users with courtesy

---

## Constraints

- Don't make up information you're unsure about
- Ask clarifying questions when needed
- Follow user instructions unless they conflict with safety guidelines
- Respect user privacy and data

---

## Capabilities

- Code development and debugging
- Problem solving and analysis
- Writing and editing
- Research and information retrieval
- File operations

---

*This file should be read first to understand AI identity*
`,

	'USER.md': `# User Preferences

> User-specific preferences and settings

---

## Communication Style

- **Language**: Vietnamese (default), English when needed
- **Tone**: Professional but friendly
- **Detail Level**: Provide enough context, avoid overwhelming

---

## Work Preferences

- **Code Style**: Clean, readable, well-commented
- **File Organization**: Logical structure
- **Testing**: Include tests when appropriate
- **Documentation**: Clear and concise

---

## Technical Preferences

- Use modern best practices
- Prefer TypeScript over JavaScript
- Use functional components for React
- Follow SOLID principles

---

## Feedback Preferences

- Let me know if something isn't working
- Feel free to ask for clarification
- Suggest improvements anytime

---

*This file defines user-specific preferences*
`,

	'GOVERNANCE.md': `# Policy Rules

> Rules and policies that govern AI behavior

---

## Safety Guidelines

1. **Don't harm** - Never provide harmful code or instructions
2. **Don't deceive** - Be honest about capabilities and limitations
3. **Don't steal** - Respect intellectual property
4. **Protect privacy** - Don't store or leak sensitive information

---

## Code of Conduct

- Be respectful and professional
- Don't generate content that violates laws
- Don't assist with illegal activities
- Don't spread misinformation

---

## Quality Standards

- Verify code before providing
- Test solutions when possible
- Document complex logic
- Consider security implications

---

## Decision Guidelines

When uncertain, ask the user:
- Is this approach acceptable?
- Do you prefer a different solution?
- Should I proceed with this implementation?

---

*This file defines policy rules for AI behavior*
`,

	'RULES.md': `# Operating Procedures

> Standard procedures and workflows

---

## Before Starting Work

1. Understand the requirements
2. Check existing codebase structure
3. Identify dependencies and requirements
4. Plan the approach

---

## During Development

1. Write clean, maintainable code
2. Add comments for complex logic
3. Test incrementally
4. Commit frequently with clear messages

---

## Code Review Checklist

- [ ] Code follows project conventions
- [ ] No console.log or debug code left behind
- [ ] Error handling is appropriate
- [ ] No hardcoded secrets or credentials
- [ ] Code is properly formatted

---

## Before Submitting

1. Run tests if available
2. Verify all features work as expected
3. Clean up temporary files
4. Update documentation if needed

---

## When Stuck

1. Search documentation
2. Check similar code in the project
3. Break down the problem
4. Ask the user for clarification

---

*This file defines standard operating procedures*
`
};

// ======================
// EXTENSION ACTIVATION
// ======================
let context: vscode.ExtensionContext;

export function activate(extContext: vscode.ExtensionContext) {
	context = extContext;

	console.log('[AI Context Master] Extension activated!');

	// Register commands
	const applyCmd = vscode.commands.registerCommand('ai-context-master.apply', applyToWorkspace);
	const setupCmd = vscode.commands.registerCommand('ai-context-master.setup', quickSetup);
	const openDocsCmd = vscode.commands.registerCommand('ai-context-master.openDocs', openDocumentation);

	// Listen for workspace folder changes
	vscode.workspace.onDidChangeWorkspaceFolders(handleWorkspaceChange);

	// Auto-inject on startup if enabled
	setTimeout(autoInjectIfEnabled, 2000);
}

// ======================
// AUTO INJECT
// ======================
async function autoInjectIfEnabled() {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const enabled = config.get<boolean>('enabled', true);
	const autoInject = config.get<boolean>('autoInject', true);

	if (!enabled || !autoInject) {
		return;
	}

	const folders = vscode.workspace.workspaceFolders;
	if (!folders || folders.length === 0) {
		return;
	}

	for (const folder of folders) {
		await injectTemplate(folder.uri.fsPath);
	}
}

async function handleWorkspaceChange(event: vscode.WorkspaceFoldersChangeEvent) {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const enabled = config.get<boolean>('enabled', true);
	const autoInject = config.get<boolean>('autoInject', true);

	if (!enabled || !autoInject) {
		return;
	}

	// Handle added folders
	for (const folder of event.added) {
		await injectTemplate(folder.uri.fsPath);
	}
}

async function injectTemplate(workspacePath: string): Promise<boolean> {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const files = config.get<string[]>('files', ['CLAUDE.md', 'SOUL.md', 'USER.md', 'GOVERNANCE.md', 'RULES.md']);
	const excludePatterns = config.get<string[]>('excludePatterns', [
		'**/node_modules/**',
		'**/.git/**',
		'**/dist/**',
		'**/build/**'
	]);

	// Check exclusions
	for (const pattern of excludePatterns) {
		if (matchGlob(workspacePath, pattern)) {
			console.log(`[AI Context Master] Skipping excluded folder: ${workspacePath}`);
			return false;
		}
	}

	// Inject each file
	let createdCount = 0;
	for (const file of files) {
		const filePath = path.join(workspacePath, file);

		if (!fs.existsSync(filePath)) {
			const template = TEMPLATES[file as keyof typeof TEMPLATES];
			if (template) {
				fs.writeFileSync(filePath, template, 'utf-8');
				console.log(`[AI Context Master] Created: ${filePath}`);
				createdCount++;
			}
		}
	}

	if (createdCount > 0) {
		vscode.window.showInformationMessage(`AI Context Master: Created ${createdCount} context file(s)!`);
	}
	return true;
}

function matchGlob(filePath: string, pattern: string): boolean {
	// Simple glob matching
	const regex = pattern
		.replace(/\*\*/g, '.*')
		.replace(/\*/g, '[^/]*')
		.replace(/\?/g, '.');
	return new RegExp(regex).test(filePath);
}

// ======================
// COMMANDS
// ======================
async function applyToWorkspace() {
	const folders = vscode.workspace.workspaceFolders;
	if (!folders || folders.length === 0) {
		vscode.window.showWarningMessage('No workspace folder open. Please open a folder first.');
		return;
	}

	// Always use default files (5 context files)
	const files = ['CLAUDE.md', 'SOUL.md', 'USER.md', 'GOVERNANCE.md', 'RULES.md'];

	// Apply to current workspace
	for (const folder of folders) {
		await injectTemplateWithFiles(folder.uri.fsPath, files);
	}
}

// Inject with custom files list
async function injectTemplateWithFiles(workspacePath: string, files: string[]): Promise<boolean> {
	const excludePatterns = [
		'**/node_modules/**',
		'**/.git/**',
		'**/dist/**',
		'**/build/**'
	];

	// Check exclusions
	for (const pattern of excludePatterns) {
		if (matchGlob(workspacePath, pattern)) {
			console.log(`[AI Context Master] Skipping excluded folder: ${workspacePath}`);
			return false;
		}
	}

	// Inject each file
	let createdCount = 0;
	for (const file of files) {
		const filePath = path.join(workspacePath, file);

		if (!fs.existsSync(filePath)) {
			const template = TEMPLATES[file as keyof typeof TEMPLATES];
			if (template) {
				fs.writeFileSync(filePath, template, 'utf-8');
				console.log(`[AI Context Master] Created: ${filePath}`);
				createdCount++;
			}
		}
	}

	if (createdCount > 0) {
		vscode.window.showInformationMessage(`AI Context Master: Created ${createdCount} context file(s)!`);
	} else {
		vscode.window.showInformationMessage('AI Context Master: Context files already exist.');
	}
	return true;
}

async function quickSetup() {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const autoInject = config.get<boolean>('autoInject', true);

	const options: vscode.QuickPickItem[] = [
		{ label: autoInject ? '✅ Disable Auto-Inject' : 'Enable Auto-Inject', description: autoInject ? 'Currently: ON' : 'Currently: OFF' },
		{ label: 'Open Documentation', description: 'View AI Context Master docs' },
		{ label: 'Configure Settings', description: 'Open settings.json' }
	];

	const choice = await vscode.window.showQuickPick(options, {
		placeHolder: 'What would you like to do?'
	});

	if (!choice) { return; }

	switch (choice.label) {
		case 'Enable Auto-Inject':
		case '✅ Disable Auto-Inject':
			const newAutoInject = !autoInject;
			await vscode.workspace.getConfiguration('aiContextMaster').update('aiContextMaster.autoInject', newAutoInject);
			vscode.window.showInformationMessage(`Auto-Inject ${newAutoInject ? 'enabled' : 'disabled'}!`);
			break;
		case 'Open Documentation':
			vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://github.com/adamwang99/ai-context-master'));
			break;
		case 'Configure Settings':
			vscode.commands.executeCommand('workbench.action.openSettings', 'aiContextMaster');
			break;
	}
}

async function openDocumentation() {
	vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://github.com/adamwang99/ai-context-master'));
}

// ======================
// EXTENSION DEACTIVATION
// ======================
export function deactivate() {
	console.log('[AI Context Master] Extension deactivated');
}
