import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// ======================
// DEFAULT TEMPLATE
// ======================
const DEFAULT_CLAUDE_MD = `# AI Context Master

> Memory Stack for AI Assistants

This project uses **AI Context Master** for enhanced AI assistance.

## Quick Start

Read these files for context:
- **SOUL.md** - AI identity & constraints
- **USER.md** - User preferences
- **GOVERNANCE.md** - Policy rules
- **RULES.md** - Operating procedures

## Features

- ✅ Automatic context loading
- ✅ Memory system for AI assistants
- ✅ Workflow automation
- ✅ Multi-agent coordination

## Setup

1. This file was auto-generated by AI Context Master extension
2. Claude (and other AI assistants) will automatically read this file
3. For more info, see [AI Context Master](https://github.com/adamwang99/ai-context-master)

---

*Powered by AI Context Master*
`;

// ======================
// EXTENSION ACTIVATION
// ======================
let context: vscode.ExtensionContext;

export function activate(extContext: vscode.ExtensionContext) {
	context = extContext;

	console.log('[AI Context Master] Extension activated!');

	// Register commands
	const applyCmd = vscode.commands.registerCommand('ai-context-master.apply', applyToWorkspace);
	const setupCmd = vscode.commands.registerCommand('ai-context-master.setup', quickSetup);
	const openDocsCmd = vscode.commands.registerCommand('ai-context-master.openDocs', openDocumentation);

	// Listen for workspace folder opened
	vscode.workspace.onDidOpenWorkspaceFolder(handleWorkspaceOpen);

	// Auto-inject on startup if enabled
	setTimeout(autoInjectIfEnabled, 2000);
}

// ======================
// AUTO INJECT
// ======================
async function autoInjectIfEnabled() {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const enabled = config.get<boolean>('enabled', true);
	const autoInject = config.get<boolean>('autoInject', true);

	if (!enabled || !autoInject) {
		return;
	}

	const folders = vscode.workspace.workspaceFolders;
	if (!folders || folders.length === 0) {
		return;
	}

	for (const folder of folders) {
		await injectTemplate(folder.uri.fsPath);
	}
}

async function handleWorkspaceOpen(folder: vscode.WorkspaceFolder) {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const enabled = config.get<boolean>('enabled', true);
	const autoInject = config.get<boolean>('autoInject', true);

	if (!enabled || !autoInject) {
		return;
	}

	await injectTemplate(folder.uri.fsPath);
}

async function injectTemplate(workspacePath: string): Promise<boolean> {
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	const files = config.get<string[]>('files', ['CLAUDE.md']);
	const excludePatterns = config.get<string[]>('excludePatterns', [
		'**/node_modules/**',
		'**/.git/**',
		'**/dist/**',
		'**/build/**'
	]);

	// Check exclusions
	for (const pattern of excludePatterns) {
		if (matchGlob(workspacePath, pattern)) {
			console.log(`[AI Context Master] Skipping excluded folder: ${workspacePath}`);
			return false;
		}
	}

	// Inject each file
	for (const file of files) {
		const filePath = path.join(workspacePath, file);

		if (!fs.existsSync(filePath)) {
			fs.writeFileSync(filePath, DEFAULT_CLAUDE_MD, 'utf-8');
			console.log(`[AI Context Master] Created: ${filePath}`);
		}
	}

	vscode.window.showInformationMessage('AI Context Master: Context applied!');
	return true;
}

function matchGlob(filePath: string, pattern: string): boolean {
	// Simple glob matching
	const regex = pattern
		.replace(/\*\*/g, '.*')
		.replace(/\*/g, '[^/]*')
		.replace(/\?/g, '.');
	return new RegExp(regex).test(filePath);
}

// ======================
// COMMANDS
// ======================
async function applyToWorkspace() {
	const folders = vscode.workspace.workspaceFolders;
	if (!folders || folders.length === 0) {
		vscode.window.showWarningMessage('No workspace folder open. Please open a folder first.');
		return;
	}

	const choice = await vscode.window.showQuickPick(
		[
			{ label: 'Minimal', description: 'CLAUDE.md only', value: ['CLAUDE.md'] },
			{ label: 'Standard', description: 'Memory Stack files', value: ['CLAUDE.md', 'SOUL.md', 'USER.md'] },
			{ label: 'Full', description: 'All context files', value: ['CLAUDE.md', 'SOUL.md', 'USER.md', 'GOVERNANCE.md', 'RULES.md'] }
		],
		{ placeHolder: 'Select template to apply' }
	);

	if (!choice) { return; }

	// Update config
	const config = vscode.workspace.getConfiguration('aiContextMaster');
	await config.update('aiContextMaster.files', choice.value);

	// Apply to current workspace
	for (const folder of folders) {
		await injectTemplate(folder.uri.fsPath);
	}
}

async function quickSetup() {
	const options: vscode.QuickPickItem[] = [
		{ label: 'Enable Auto-Inject', description: 'Automatically apply context to new folders' },
		{ label: 'Disable Auto-Inject', description: 'Manually apply context when needed' },
		{ label: 'Open Documentation', description: 'View AI Context Master docs' },
		{ label: 'Configure Settings', description: 'Open settings.json' }
	];

	const choice = await vscode.window.showQuickPick(options, {
		placeHolder: 'What would you like to do?'
	});

	if (!choice) { return; }

	switch (choice.label) {
		case 'Enable Auto-Inject':
			await vscode.workspace.getConfiguration('aiContextMaster').update('aiContextMaster.autoInject', true);
			vscode.window.showInformationMessage('Auto-Inject enabled!');
			break;
		case 'Disable Auto-Inject':
			await vscode.workspace.getConfiguration('aiContextMaster').update('aiContextMaster.autoInject', false);
			vscode.window.showInformationMessage('Auto-Inject disabled.');
			break;
		case 'Open Documentation':
			vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://github.com/adamwang99/ai-context-master'));
			break;
		case 'Configure Settings':
			vscode.commands.executeCommand('workbench.action.openSettings', 'aiContextMaster');
			break;
	}
}

async function openDocumentation() {
	vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://github.com/adamwang99/ai-context-master'));
}

// ======================
// EXTENSION DEACTIVATION
// ======================
export function deactivate() {
	console.log('[AI Context Master] Extension deactivated');
}
